// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBONTJkuoF7enR2geaXQFeJoo-sR0M5jI8',
    appId: '1:855638815927:web:18c3fcfa8c6b8a25144932',
    messagingSenderId: '855638815927',
    projectId: 'e-learningapp-ce486',
    authDomain: 'e-learningapp-ce486.firebaseapp.com',
    storageBucket: 'e-learningapp-ce486.firebasestorage.app',
    measurementId: 'G-PREP8PSSEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBciokdvY9XD-AF-tx3eZoqbXZ4JaUuFb8',
    appId: '1:855638815927:android:4817cf9c5479ea4e144932',
    messagingSenderId: '855638815927',
    projectId: 'e-learningapp-ce486',
    storageBucket: 'e-learningapp-ce486.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8WaJnfadcpcEDXoohibz7juLoCETreno',
    appId: '1:855638815927:ios:316b9bbed9322d1b144932',
    messagingSenderId: '855638815927',
    projectId: 'e-learningapp-ce486',
    storageBucket: 'e-learningapp-ce486.firebasestorage.app',
    iosBundleId: 'com.example.eLearningPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8WaJnfadcpcEDXoohibz7juLoCETreno',
    appId: '1:855638815927:ios:316b9bbed9322d1b144932',
    messagingSenderId: '855638815927',
    projectId: 'e-learningapp-ce486',
    storageBucket: 'e-learningapp-ce486.firebasestorage.app',
    iosBundleId: 'com.example.eLearningPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBONTJkuoF7enR2geaXQFeJoo-sR0M5jI8',
    appId: '1:855638815927:web:e0926f1ab874494a144932',
    messagingSenderId: '855638815927',
    projectId: 'e-learningapp-ce486',
    authDomain: 'e-learningapp-ce486.firebaseapp.com',
    storageBucket: 'e-learningapp-ce486.firebasestorage.app',
    measurementId: 'G-26F20S90XF',
  );
}
